# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  Name: jenkins-master
  Image: "pinterb/jenkins-master-k8s"
  ImageTag: "2.19.3"
  ImagePullPolicy: "Always"
  Component: "jenkins-master"
  AdminUser: admin
# AdminPassword: <defaults to random>
  Cpu: "200m"
  Memory: "512Mi"
# Set min/max heap here if needed with:
# JavaOpts: "-Xms512m -Xmx512m"
  ServicePort: 8080
# For minikube, set this to NodePort, elsewhere use LoadBalancer
  ServiceType: LoadBalancer
  ContainerPort: 8080
  SlaveListenerPort: 50000

Agent:
  Image: pinterb/jenkins-jnlp-slave
  ImageTag: 2.62
  Cpu: "350m"
  Memory: "768Mi"

Persistence:
  Enabled: true
  StorageClass: generic
  AccessMode: ReadWriteOnce
  Size: 8Gi
